# Generated by Django 6.0 on 2025-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_leaverequest_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='message',
            field=models.CharField(blank=True, null=True),
        ),
    ]
